In [2]:
import geopandas
import pandas as pd

## Kreuzberg: Heat map of connectivity to other Berlin districts from Kreuzberg
Measured by counting for each district, how many stops it includes that are reachable from Kreuzberg

Import Filtered Dataset: Lines that run through Kreuzberg 
<br> --> for cross-referencing with all stops to get all stops that are reachable from Kreuzberg

In [3]:
Kreuzberg_lines_df = pd.read_csv("FilteredDataset/Kreuzberg_lines.csv")
Kreuzberg_lines_df

,Unnamed: 0,line_id,jahr,linien_name,typ,dauer (min),ost_west,frequenz,länge (km),start,ziel
0,0,19461,1946,1,autobus,NaN,both/unkown,25,NaN,Flughafen,Alt-Friedrichsfelde
1,1,19462,1946,1,straßenbahn,15.0,both/unkown,10,NaN,Hackescher Markt,Anhalter Bahnhof
2,2,19464,1946,21,straßenbahn,15.0,both/unkown,6,NaN,Wiebestrasse,Anhalter Bhf.
3,3,194612,1946,3,straßenbahn,NaN,both/unkown,10,NaN,Gotzkowskystrasse,Gardepionierplatz
4,4,194644,1946,87,straßenbahn,30.0,both/unkown,10,NaN,Dönhoffplatz,Rahnsdorf
...,...,...,...,...,...,...,...,...,...,...,...
244,244,1989133,1989,6,u-bahn,37.0,west,3,NaN,Tegel,Alt-Mariendorf
245,245,1989134,1989,7,u-bahn,56.0,west,12,NaN,Rathaus Spandau,Rudow
246,246,1989135,1989,8,u-bahn,27.0,west,5,NaN,Paracelsus-Bad,Leinestrasse
247,247,1989137,1989,1,s-bahn,30.0,west,10,NaN,Anhalter Bahnhof,Wannsee
248,248,1989138,1989,2,s-bahn,53.0,west,10,NaN,Frohnau,Lichtenrade

Filter and Export (for future use/reference)

In [4]:
Kreuzberg_lines_df_1984 = Kreuzberg_lines_df[Kreuzberg_lines_df["jahr"]==1984]
Kreuzberg_lines_df_1984

,Unnamed: 0,line_id,jahr,linien_name,typ,dauer (min),ost_west,frequenz,länge (km),start,ziel
221,221,198421,1984,19,autobus,44.0,West,10,NaN,Grunewald Roseneck,Platz der Luftbrücke
222,222,198433,1984,24,autobus,43.0,West,15,NaN,Moabit Wiebestrasse,Platz der Luftbrücke
223,223,198439,1984,28,autobus,44.0,West,15,NaN,U-Bhf. Tempelhof,Schlesische Strasse Ecke Heckmannufer
224,224,198462,1984,4,autobus,64.0,West,10,NaN,"Neu-Westend, Brixplatz","Neukölln, Teupitzer Strasse"
225,225,198466,1984,41,autobus,58.0,West,12,NaN,Rudow Stadtgrenze,U-Bhf. Hallesches Tor
226,226,1984123,1984,75,autobus,54.0,West,10,NaN,Steglitzer Damm Ecke Munsterdamm,Hermannplatz
227,227,1984162,1984,96,autobus,33.0,West,12,NaN,Platz der Luftbrücke,Lichterfelde Lindenstrasse
228,228,1984163,1984,96E,autobus,43.0,West,12,NaN,Platz der Luftbrücke,Beeskowdamm
229,229,1984173,1984,1,u-bahn,31.0,West,6,NaN,Schlesisches Tor,Ruhleben
230,230,1984177,1984,6,u-bahn,37.0,West,3,NaN,Tegel,Alt-Mariendorf
231,231,1984178,1984,7,u-bahn,46.0,West,3,NaN,Rohrdamm,Rudow
232,232,1984179,1984,8,u-bahn,23.0,West,6,NaN,Osloer Strasse,Leinestrasse
233,233,1984181,1984,2,s-bahn,34.0,West,20,NaN,Lichtenrade,Gesundbrunnen

In [5]:
Kreuzberg_lines_df_1984.to_csv("FilteredDataset/Kreuzberg_lines_1984.csv")

Import Original Dataset: Line Stops

In [6]:
line_stops_df = pd.read_csv("PublicTransitDataset/line_stops.csv")

In [7]:
line_stops_df

       line_id  stop_order   stop_id
0        19461           0   1946151
1        19461           1   1946158
2        19461           2   1946212
3        19461           3   1946325
4        19461           4   1946257
...        ...         ...       ...
28977  1989198           8    198944
28978  1989198           9   1989501
28979  1989198          10  19891912
28980  1989198          11  19891172
28981  1989198          12  19891860

[28982 rows x 3 columns]

Create base list to fill in Boolean value of connected/not connected to Kreuzberg

In [8]:
line_stops_kreuzberg_boo = [0]*len(line_stops_df["line_id"])
#print(line_stops_kreuzberg_boo)

Determine whether each stop is a part of a line that services Kreuzberg

In [9]:

for i, line_id in enumerate(line_stops_df["line_id"]):
    print(line_id)
    if line_id in list(Kreuzberg_lines_df["line_id"]): # change value in list above to match whether each stop is relevant to Kreuzberg
        line_stops_kreuzberg_boo[i]=True 
    else:
        line_stops_kreuzberg_boo[i]=False

19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19461
19462
19462
19462
19462
19462
19462
19462
19462
19462
19462
19462
19462
19462
19463
19463
19463
19463
19463
19464
19464
19464
19464
19464
19464
19464
19464
19464
19464
19464
19464
19465
19465
19465
19465
19465
19465
19465
19465
19465
19465
19465
19465
19465
19466
19466
19466
19466
19466
19466
19466
19466
19467
19467
19467
19467
19467
19468
19468
19468
19468
19468
19468
19468
19468
19468
19468
19468
19468
19468
19468
19468
19468
19468
19468
19469
19469
19469
19469
19469
19469
19469
19469
19469
19469
19469
19469
19469
19469
19469
19469
19469
194610
194610
194610
194610
194610
194610
194611
194611
194611
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194612
194613
194613
194613
194613
194613
194613
194613
194613
194613
194614
194614
194614
194614
194614
194614
194614
194614
194614
194614
194615
194615
194615
194615
194615
194615
194615
194615
194615
194615
194615
194616
194616
194616
194616
194616
194616
194616
194617
194617
194617
194618
194618
194618
194618
194618
194618
194618
194618
194619
194619
194619
194619
194619
194619
194619
194619
194619
194619
194619
194619
194619
194619
194619
194619
194619
194620
194620
194620
194620
194620
194620
194620
194620
194620
194620
194620
194620
194620
194620
194620
194620
194620
194621
194621
194621
194621
194621
194621
194621
194621
194621
194621
194621
194621
194621
194621
194621
194621
194621
194622
194622
194622
194622
194622
194622
194622
194622
194622
194622
194622
194622
194622
194623
194623
194623
194623
194623
194623
194623
194623
194623
194623
194623
194623
194624
194624
194624
194624
194624
194624
194625
194625
194625
194625
194625
194625
194625
194625
194625
194625
194626
194626
194626
194626
194626
194626
194626
194626
194626
194626
194626
194626
194626
194626
194627
194627
194627
194627
194627
194627
194627
194627
194627
194627
194628
194628
194628
194628
194628
194628
194628
194628
194628
194628
194628
194629
194629
194629
194629
194629
194629
194629
194629
194629
194629
194629
194629
194629
194630
194630
194630
194630
194630
194630
194630
194630
194630
194631
194631
194631
194631
194631
194631
194631
194631
194632
194632
194632
194632
194632
194632
194632
194632
194633
194633
194633
194633
194633
194633
194633
194633
194633
194633
194633
194633
194634
194634
194634
194634
194634
194634
194634
194634
194634
194634
194634
194635
194635
194635
194635
194635
194635
194635
194635
194635
194635
194636
194636
194636
194636
194636
194636
194636
194636
194636
194636
194636
194636
194636
194637
194637
194637
194637
194637
194637
194637
194637
194637
194637
194637
194638
194638
194638
194638
194638
194638
194638
194638
194638
194638
194638
194639
194639
194639
194639
194639
194639
194639
194640
194640
194640
194640
194640
194640
194640
194640
194640
194640
194640
194640
194641
194641
194641
194641
194641
194641
194641
194643
194643
194643
194643
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194644
194645
194645
194645
194645
194645
194645
194646
194646
194646
194646
194646
194646
194646
194646
194646
194646
194646
194646
194646
194646
194646
194646
194646
194647
194647
194647
194647
194647
194647
194647
194647
194647
194647
194648
194648
194648
194648
194648
194648
194648
194648
194648
194648
194648
194649
194649
194649
194649
194649
194649
194649
194649
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194650
194651
194651
194651
194651
194651
194651
194651
194651
194652
194652
194652
194652
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194653
194654
194654
194654
194655
194655
194655
194655
194655
194655
194655
194655
194655
194655
194655
194655
194656
194656
194656
194656
194656
194656
194656
194656
194656
194657
194657
194657
194657
194657
194657
194657
194657
194657
194657
194657
194657
194657
194657
194657
194657
194658
194658
194658
194658
194658
194658
194658
194658
194658
194658
194658
194658
194658
194658
194658
194658
194658
194658
194659
194659
194659
194659
194659
194659
194659
194659
194659
194659
194659
194659
194659
194659
194659
194660
194660
194660
194660
194660
194660
194660
194660
194660
194660
194660
194660
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194661
194662
194662
194662
194662
194662
194662
194662
194662
194662
194662
194662
194662
194662
194662
194662
194663
194663
194663
194663
194663
194663
194663
194663
194663
194663
194664
194664
194664
194664
194664
194664
194664
194664
194664
194664
194664
194664
194664
194665
194665
194665
194665
194665
194665
194666
194666
194666
194666
194667
194667
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194668
194669
194669
194669
194669
194669
194669
194669
194669
194669
194669
194669
194669
194669
194669
194670
194670
194670
194670
194670
194670
194670
194670
194670
194670
194671
194671
194671
19511
19511
19511
19511
19511
19511
19511
19511
19511
19511
19511
19511
19512
19512
19512
19512
19512
19512
19512
19512
19512
19512
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19513
19514
19514
19514
19514
19514
19514
19514
19514
19514
19514
19514
19514
19515
19515
19515
19515
19515
19515
19515
19515
19515
19515
19515
19516
19516
19516
19516
19516
19516
19516
19516
19516
19516
19516
19516
19516
19517
19517
19517
19517
19517
19517
19517
19518
19518
19518
19518
19518
19518
19518
19518
19518
19519
19519
19519
19519
19519
19519
19519
195110
195110
195110
195110
195110
195110
195110
195110
195110
195110
195110
195111
195111
195111
195111
195111
195111
195111
195111
195111
195111
195111
195112
195112
195112
195112
195112
195112
195112
195112
195112
195112
195113
195113
195113
195113
195113
195113
195113
195113
195113
195113
195113
195113
195113
195113
195113
195113
195113
195113
195114
195114
195114
195114
195114
195114
195114
195114
195115
195115
195115
195115
195115
195115
195116
195116
195116
195116
195116
195116
195116
195116
195116
195116
195116
195116
195116
195117
195117
195117
195117
195117
195117
195117
195117
195117
195117
195117
195117
195117
195118
195118
195118
195118
195118
195118
195118
195118
195118
195118
195119
195119
195119
195119
195119
195119
195120
195120
195120
195120
195120
195120
195121
195121
195121
195121
195121
195121
195121
195121
195121
195121
195121
195122
195122
195122
195122
195122
195122
195122
195122
195122
195122
195122
195122
195122
195122
195122
195122
195122
195123
195123
195123
195123
195123
195123
195123
195123
195123
195123
195123
195123
195123
195123
195123
195123
195124
195124
195124
195124
195124
195124
195124
195124
195124
195124
195124
195124
195125
195125
195125
195125
195125
195125
195125
195125
195125
195125
195125
195125
195125
195126
195126
195126
195126
195126
195127
195127
195127
195127
195127
195127
195127
195127
195127
195127
195127
195128
195128
195128
195128
195128
195128
195128
195128
195128
195128
195128
195128
195128
195129
195129
195129
195129
195129
195130
195130
195130
195130
195130
195130
195130
195130
195130
195130
195130
195130
195130
195131
195131
195131
195131
195131
195131
195131
195131
195131
195131
195131
195131
195131
195132
195132
195132
195132
195132
195132
195132
195132
195132
195133
195133
195133
195134
195134
195134
195134
195134
195134
195134
195135
195135
195135
195135
195135
195135
195135
195135
195135
195136
195136
195136
195136
195136
195136
195136
195136
195136
195137
195137
195137
195137
195137
195137
195138
195138
195138
195138
195138
195138
195138
195138
195138
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195139
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195140
195141
195141
195141
195141
195141
195141
195141
195141
195141
195141
195141
195141
195141
195142
195142
195142
195142
195142
195142
195142
195142
195142
195143
195143
195143
195143
195143
195143
195143
195143
195143
195144
195144
195144
195144
195144
195144
195144
195144
195144
195144
195144
195144
195144
195144
195144
195144
195145
195145
195145
195145
195145
195145
195145
195145
195145
195145
195146
195146
195146
195146
195146
195146
195146
195146
195147
195147
195147
195147
195147
195147
195147
195147
195148
195148
195148
195148
195148
195148
195148
195149
195149
195149
195149
195149
195149
195149
195149
195149
195149
195149
195149
195149
195149
195150
195150
195150
195150
195150
195150
195150
195150
195150
195150
195150
195150
195150
195150
195150
195151
195151
195151
195151
195151
195151
195151
195151
195151
195151
195151
195151
195151
195152
195152
195152
195152
195153
195153
195153
195153
195153
195153
195153
195153
195154
195154
195154
195154
195154
195154
195154
195154
195154
195154
195154
195154
195154
195155
195155
195155
195155
195155
195155
195155
195155
195155
195155
195155
195156
195156
195156
195156
195156
195156
195156
195157
195157
195157
195157
195157
195157
195157
195157
195157
195157
195157
195157
195158
195158
195158
195158
195158
195158
195158
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195159
195160
195160
195160
195160
195160
195160
195160
195160
195160
195160
195160
195160
195160
195161
195161
195162
195162
195162
195162
195162
195162
195162
195162
195162
195162
195162
195162
195162
195162
195163
195163
195163
195163
195163
195163
195163
195163
195163
195163
195163
195163
195164
195164
195164
195164
195164
195164
195164
195165
195165
195165
195165
195165
195165
195165
195165
195165
195165
195166
195166
195166
195166
195166
195166
195166
195166
195166
195166
195166
195166
195166
195167
195167
195167
195167
195167
195167
195167
195167
195168
195168
195168
195168
195168
195168
195168
195169
195169
195169
195169
195169
195169
195169
195169
195169
195169
195169
195169
195169
195169
195170
195170
195170
195170
195170
195170
195170
195170
195170
195170
195171
195171
195171
195171
195171
195171
195172
195172
195172
195172
195172
195172
195172
195172
195172
195173
195173
195173
195173
195173
195173
195173
195173
195173
195173
195174
195174
195174
195174
195174
195174
195174
195174
195174
195174
195175
195175
195175
195175
195175
195176
195176
195176
195176
195176
195176
195176
195176
195177
195177
195177
195177
195177
195177
195178
195178
195178
195178
195178
195178
195178
195178
195178
195179
195179
195179
195179
195179
195180
195180
195180
195180
195180
195181
195181
195181
195181
195181
195181
195182
195182
195182
195182
195183
195183
195183
195183
195183
195184
195184
195184
195184
195184
195185
195185
195185
195185
195185
195185
195186
195186
195186
195186
195186
195186
195186
195187
195187
195187
195187
195187
195187
195188
195188
195188
195188
195188
195188
195188
195188
195189
195189
195189
195189
195189
195190
195190
195190
195191
195191
195191
195191
195191
195191
195191
195191
195191
195191
195191
195191
195191
195192
195192
195192
195192
195192
195192
195193
195193
195193
195193
195194
195194
195194
195194
195194
195194
195194
195194
195195
195195
195195
195195
195195
195196
195196
195196
195196
195196
195197
195197
195197
195197
195197
195197
195197
195197
195197
195197
195198
195198
195198
195198
195198
195198
195198
195198
195198
195198
195198
195198
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
195199
1951100
1951100
1951100
1951100
1951101
1951101
1951101
1951101
1951101
1951101
1951101
1951101
1951101
1951101
1951101
1951101
1951101
1951101
1951102
1951102
1951102
1951102
1951102
1951102
1951102
1951102
1951102
1951102
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951103
1951104
1951104
1951104
1951104
1951104
1951104
1951104
1951104
1951104
1951104
1951104
1951104
1951104
1951105
1951105
1951105
1951105
1951106
1951106
1951106
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951107
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951108
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951109
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951110
1951111
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951112
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951113
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951114
1951115
1951115
19561
19561
19561
19561
19561
19561
19561
19561
19561
19561
19561
19561
19562
19562
19562
19562
19562
19562
19562
19562
19562
19562
19562
19562
19562
19562
19562
19563
19563
19563
19563
19563
19563
19563
19563
19563
19563
19563
19563
19563
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19564
19565
19565
19565
19565
19565
19565
19565
19565
19565
19565
19565
19565
19566
19566
19566
19566
19566
19566
19566
19566
19566
19566
19566
19566
19566
19566
19566
19567
19567
19567
19567
19567
19567
19567
19567
19567
19567
19568
19568
19568
19568
19568
19568
19568
19568
19568
19568
19568
19568
19568
19568
19568
19569
19569
19569
19569
19569
19569
19569
19569
19569
19569
19569
19569
19569
19569
195610
195610
195610
195610
195610
195610
195610
195610
195610
195610
195610
195610
195610
195610
195610
195611
195611
195611
195611
195611
195611
195611
195611
195611
195611
195611
195612
195612
195612
195612
195612
195612
195612
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195613
195614
195614
195614
195614
195614
195614
195614
195614
195614
195614
195614
195614
195615
195615
195615
195615
195615
195615
195616
195616
195616
195616
195616
195616
195616
195616
195616
195616
195616
195616
195616
195616
195616
195616
195617
195617
195617
195617
195617
195617
195617
195617
195617
195617
195617
195617
195617
195617
195617
195617
195618
195618
195618
195618
195618
195618
195618
195618
195618
195618
195618
195618
195618
195618
195618
195618
195619
195619
195619
195619
195619
195619
195619
195619
195619
195619
195620
195620
195620
195620
195620
195620
195620
195620
195621
195621
195621
195621
195621
195621
195621
195621
195621
195621
195621
195621
195621
195621
195621
195622
195622
195622
195622
195622
195622
195622
195622
195622
195622
195622
195622
195622
195622
195622
195622
195622
195623
195623
195623
195623
195623
195623
195623
195623
195623
195623
195623
195623
195623
195623
195623
195623
195624
195624
195624
195624
195624
195624
195624
195624
195624
195624
195624
195625
195625
195625
195625
195625
195625
195625
195625
195625
195625
195625
195625
195625
195626
195626
195626
195626
195626
195626
195627
195627
195627
195627
195627
195627
195627
195627
195627
195627
195627
195627
195627
195627
195627
195627
195627
195627
195628
195628
195628
195628
195628
195628
195628
195628
195628
195628
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195629
195630
195630
195630
195630
195630
195630
195630
195630
195630
195630
195630
195630
195630
195631
195631
195631
195631
195631
195631
195631
195631
195631
195631
195631
195631
195631
195632
195632
195632
195632
195632
195632
195632
195632
195633
195633
195633
195633
195633
195633
195633
195633
195634
195634
195634
195634
195634
195634
195634
195634
195634
195634
195634
195634
195634
195634
195634
195634
195634
195634
195635
195635
195635
195635
195635
195635
195635
195635
195635
195635
195635
195635
195635
195635
195636
195636
195636
195636
195636
195636
195636
195636
195636
195637
195637
195637
195637
195637
195637
195637
195637
195637
195637
195637
195638
195638
195638
195638
195638
195638
195638
195638
195638
195638
195638
195638
195638
195638
195639
195639
195639
195639
195639
195639
195639
195639
195639
195639
195640
195640
195640
195640
195640
195640
195640
195640
195640
195640
195641
195641
195641
195641
195641
195641
195641
195641
195641
195641
195641
195641
195641
195641
195641
195641
195641
195641
195642
195642
195642
195642
195642
195642
195642
195642
195642
195642
195642
195642
195642
195642
195642
195642
195643
195643
195643
195643
195643
195643
195643
195643
195643
195643
195643
195643
195643
195643
195643
195643
195644
195644
195644
195644
195644
195644
195644
195644
195644
195644
195644
195644
195644
195644
195644
195644
195645
195645
195645
195645
195645
195645
195645
195645
195645
195645
195646
195646
195646
195646
195646
195646
195646
195646
195646
195646
195646
195646
195646
195646
195647
195647
195647
195647
195647
195647
195647
195647
195647
195647
195647
195647
195647
195648
195648
195648
195648
195648
195648
195648
195648
195648
195648
195648
195648
195648
195648
195648
195649
195649
195649
195649
195649
195649
195649
195649
195649
195649
195649
195649
195649
195649
195649
195649
195650
195650
195650
195650
195650
195650
195650
195651
195651
195651
195651
195651
195651
195651
195652
195652
195652
195652
195652
195652
195652
195652
195653
195653
195653
195653
195653
195653
195653
195653
195653
195653
195653
195653
195653
195653
195653
195653
195654
195654
195654
195654
195654
195654
195654
195654
195655
195655
195655
195655
195655
195655
195655
195655
195655
195655
195656
195656
195656
195656
195656
195656
195656
195657
195657
195657
195657
195657
195657
195657
195657
195657
195657
195657
195657
195657
195658
195658
195658
195658
195658
195658
195658
195658
195658
195658
195658
195658
195658
195658
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195659
195660
195660
195660
195660
195660
195660
195660
195660
195660
195660
195660
195660
195660
195660
195660
195660
195660
195660
195661
195661
195662
195662
195662
195662
195662
195662
195662
195662
195662
195662
195662
195662
195662
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195663
195664
195664
195664
195664
195664
195664
195664
195664
195664
195664
195664
195664
195664
195664
195665
195665
195665
195665
195665
195665
195665
195665
195665

Add column to line stops dataframe of whether or not the stop is reachable from Kreuzberg as "Kreuzberg_included"

In [10]:
line_stops_df.insert(3,"Kreuzberg_included",line_stops_kreuzberg_boo)

In [11]:
line_stops_df

       line_id  stop_order   stop_id  Kreuzberg_included
0        19461           0   1946151                True
1        19461           1   1946158                True
2        19461           2   1946212                True
3        19461           3   1946325                True
4        19461           4   1946257                True
...        ...         ...       ...                 ...
28977  1989198           8    198944               False
28978  1989198           9   1989501               False
28979  1989198          10  19891912               False
28980  1989198          11  19891172               False
28981  1989198          12  19891860               False

[28982 rows x 4 columns]

Filter dataframe for only those stops connected to Kreuzberg, export

In [12]:
line_stops_df_Kreuzberg = line_stops_df[line_stops_df["Kreuzberg_included"] == True]

In [13]:
line_stops_df_Kreuzberg

       line_id  stop_order   stop_id  Kreuzberg_included
0        19461           0   1946151                True
1        19461           1   1946158                True
2        19461           2   1946212                True
3        19461           3   1946325                True
4        19461           4   1946257                True
...        ...         ...       ...                 ...
28322  1989138          13  19891697                True
28323  1989138          14  19891376                True
28324  1989138          15  19891380                True
28325  1989138          16   1989351                True
28326  1989138          17  19891275                True

[4527 rows x 4 columns]

In [14]:
line_stops_df_Kreuzberg.to_csv("FilteredDataset/Kreuzberg_line_stops.csv")

Import Original Dataset: all stations
<br> --> will give coordinates with which the district each stop belongs to will be determined

In [15]:
stations_df = pd.read_csv("PublicTransitDataset/stations.csv")
stations_df

,stop_id,stop_name,typ,standort,in_linien,wikidata_id
0,19460,Adlershof,s-bahn,"52.434722222222,13.541388888889","['KBS 100a', 'KBS 100c']",Q323551
1,19461,Akazienallee,omnibus,"52.47849809201335, 13.607179083668733",['D'],NaN
2,19462,Alexanderplatz,omnibus,"52.52005246558073, 13.413957243449447","['1', '9']",NaN
3,19463,Alexanderplatz,s-bahn,"52.521388888889,13.411944444444","['KBS 100c', 'KBS 101']",Q111324700
4,19464,Alexanderplatz,straßenbahn,"52.5219449,13.4143847","['60', '64', '65', '72', '73']",Q65548996
...,...,...,...,...,...,...
19753,19892663,kantstr.,autobus,"52.50531710941182, 13.331624484752632",['60'],NaN
19754,19892664,katzbachstr.,autobus,"52.49157231856929, 13.376684416851326",['19'],NaN
19755,19892665,neuhoferstr.,autobus,"52.411694901653036, 13.503489970696608",['58'],NaN
19756,19892666,Öschebronnerweg,autobus,"52.61154475375042, 13.337669105320359",['20'],NaN
19757,19892667,Übergang,autobus,"52.543078667825824, 13.157884773521127",['63'],NaN

Create base list for boolean determination of connected to / not connected to Kreuzberg

In [16]:
Kreuzberg_connected_boo = [0]*len(stations_df["stop_id"])

determine whether each stop is connected to Kreuzberg

In [17]:
for i, stop_id in enumerate(stations_df["stop_id"]):
    if stop_id in list(line_stops_df_Kreuzberg["stop_id"]):
        Kreuzberg_connected_boo[i] = True
    else:
        Kreuzberg_connected_boo[i] = False

Add boolean value to dataframe

In [18]:
stations_df.insert(6,"Kreuzberg_connected",Kreuzberg_connected_boo)
stations_df

,stop_id,stop_name,typ,standort,in_linien,wikidata_id,Kreuzberg_connected
0,19460,Adlershof,s-bahn,"52.434722222222,13.541388888889","['KBS 100a', 'KBS 100c']",Q323551,False
1,19461,Akazienallee,omnibus,"52.47849809201335, 13.607179083668733",['D'],NaN,False
2,19462,Alexanderplatz,omnibus,"52.52005246558073, 13.413957243449447","['1', '9']",NaN,True
3,19463,Alexanderplatz,s-bahn,"52.521388888889,13.411944444444","['KBS 100c', 'KBS 101']",Q111324700,False
4,19464,Alexanderplatz,straßenbahn,"52.5219449,13.4143847","['60', '64', '65', '72', '73']",Q65548996,False
...,...,...,...,...,...,...,...
19753,19892663,kantstr.,autobus,"52.50531710941182, 13.331624484752632",['60'],NaN,False
19754,19892664,katzbachstr.,autobus,"52.49157231856929, 13.376684416851326",['19'],NaN,True
19755,19892665,neuhoferstr.,autobus,"52.411694901653036, 13.503489970696608",['58'],NaN,False
19756,19892666,Öschebronnerweg,autobus,"52.61154475375042, 13.337669105320359",['20'],NaN,False
19757,19892667,Übergang,autobus,"52.543078667825824, 13.157884773521127",['63'],NaN,False

Filter dataframe for only those stations connected to Kreuzberg

In [19]:
Kreuzberg_connected_stations_df = stations_df[stations_df["Kreuzberg_connected"]==True]
Kreuzberg_connected_stations_df

,stop_id,stop_name,typ,standort,in_linien,wikidata_id,Kreuzberg_connected
2,19462,Alexanderplatz,omnibus,"52.52005246558073, 13.413957243449447","['1', '9']",NaN,True
5,19465,Alexanderplatz,u-bahn,"52.5214,13.4119","['A', 'D', 'E']",Q17173458,True
6,19466,Alexanderstr.,omnibus,"52.51778540833277, 13.418077932963259",['1'],NaN,True
8,19468,Alt-Friedrichsfelde,omnibus,"52.51072943298707, 13.504877027235766","['1', 'H']",NaN,True
11,194611,Alt-Moabit,straßenbahn,"52.522953428732706, 13.363110996619637",['21'],NaN,True
...,...,...,...,...,...,...,...
19721,19892631,Ziegrastr.,autobus,"52.472749919337474, 13.45812135865549","['41', '95']",NaN,True
19731,19892641,Zitadelle,u-bahn,"52.537777777778,13.217777777778",['7'],Q663212,True
19735,19892645,Zoologischer Garten,u-bahn,"52.5058669,13.3330236","['1', '9']",Q4024764,True
19745,19892655,Zwickauerdamm,u-bahn,"52.423333333333,13.483888888889",['7'],Q572096,True
19754,19892664,katzbachstr.,autobus,"52.49157231856929, 13.376684416851326",['19'],NaN,True

Format co-ordinates in to GeoPandas form

In [20]:
K_latlist = list()
K_longlist = list()
for i, stop in enumerate(Kreuzberg_connected_stations_df["standort"]):
    latlong = stop.split(",")
    K_latlist.append(latlong[0])
    K_longlist.append(latlong[1])

In [21]:
K_pointdataframe = pd.DataFrame({'longitude': K_longlist, 'latitude': K_latlist})
K_points = geopandas.points_from_xy(K_pointdataframe.longitude, K_pointdataframe.latitude, crs="EPSG:4326")
K_points = K_points.to_crs("EPSG:4326")

Add GeoPandas co-ordinates to dataframe

In [22]:
Kreuzberg_connected_stations_df.insert(5,"Point",K_points)

Give the year for each stop by determining it from the stop id, which starts with the year

In [23]:
year = list()
for stop_id in Kreuzberg_connected_stations_df["stop_id"]:
    year.append(str(stop_id)[0:4])

Add the year of each stop to the dataframe

In [24]:
Kreuzberg_connected_stations_df.insert(1,"year",year)
Kreuzberg_connected_stations_df

,stop_id,year,stop_name,typ,standort,in_linien,Point,wikidata_id,Kreuzberg_connected
2,19462,1946,Alexanderplatz,omnibus,"52.52005246558073, 13.413957243449447","['1', '9']",POINT (13.41396 52.52005),NaN,True
5,19465,1946,Alexanderplatz,u-bahn,"52.5214,13.4119","['A', 'D', 'E']",POINT (13.4119 52.5214),Q17173458,True
6,19466,1946,Alexanderstr.,omnibus,"52.51778540833277, 13.418077932963259",['1'],POINT (13.41808 52.51779),NaN,True
8,19468,1946,Alt-Friedrichsfelde,omnibus,"52.51072943298707, 13.504877027235766","['1', 'H']",POINT (13.50488 52.51073),NaN,True
11,194611,1946,Alt-Moabit,straßenbahn,"52.522953428732706, 13.363110996619637",['21'],POINT (13.36311 52.52295),NaN,True
...,...,...,...,...,...,...,...,...,...
19721,19892631,1989,Ziegrastr.,autobus,"52.472749919337474, 13.45812135865549","['41', '95']",POINT (13.45812 52.47275),NaN,True
19731,19892641,1989,Zitadelle,u-bahn,"52.537777777778,13.217777777778",['7'],POINT (13.21778 52.53778),Q663212,True
19735,19892645,1989,Zoologischer Garten,u-bahn,"52.5058669,13.3330236","['1', '9']",POINT (13.33302 52.50587),Q4024764,True
19745,19892655,1989,Zwickauerdamm,u-bahn,"52.423333333333,13.483888888889",['7'],POINT (13.48389 52.42333),Q572096,True
19754,19892664,1989,katzbachstr.,autobus,"52.49157231856929, 13.376684416851326",['19'],POINT (13.37668 52.49157),NaN,True

In [25]:
Kreuzberg_connected_stations_df.to_csv("AnalysisDataset/Kreuzberg_connected_stations_allyears.csv")

Note: From here, re-run with each change in year

Year Selection:
- 1951
- 1961
- (1964)
- 1967
- 1976
- 1984

Import Berlin Districts Data: this gives the polygons defining each district, allowing each stop reachable from Kreuzberg to be categorized as a part of a district

In [66]:
berlin_gdf = geopandas.read_file("BerlinDistricts.gdb")
berlin_gdf = berlin_gdf.to_crs("EPSG:4326")
berlin_gdf = berlin_gdf.set_index("name")
berlin_gdf

,schlüssel,gdf,SHAPE_Length,SHAPE_Area,geometry
name,,,,,
Rahnsdorf,110000090912,21442809.0,50943.190174,5.761442e+07,"MULTIPOLYGON (((13.70385 52.45481, 13.70461 52..."
Rudow,110000080804,11818287.0,27441.756160,3.171547e+07,"MULTIPOLYGON (((13.47869 52.44274, 13.47875 52..."
Charlottenburg-Nord,110000040406,6199488.0,18719.891497,1.673023e+07,"MULTIPOLYGON (((13.27196 52.54939, 13.27209 52..."
Siemensstadt,110000050503,5663969.0,21852.474844,1.528409e+07,"MULTIPOLYGON (((13.24096 52.55602, 13.24113 52..."
Hakenfelde,110000050507,20381270.0,37928.645962,5.508595e+07,"MULTIPOLYGON (((13.20221 52.58804, 13.20253 52..."
...,...,...,...,...,...
Wannsee,110000060607,23735618.0,52313.210225,6.370469e+07,"MULTIPOLYGON (((13.16655 52.44252, 13.16723 52..."
Wedding,110000010105,9245378.0,23763.290521,2.496165e+07,"MULTIPOLYGON (((13.3569 52.56202, 13.35709 52...."
Lichterfelde,110000060602,18226316.0,36848.267479,4.893303e+07,"MULTIPOLYGON (((13.3071 52.45893, 13.30689 52...."
Lankwitz,110000060603,6989951.0,18111.014874,1.877084e+07,"MULTIPOLYGON (((13.33452 52.4456, 13.33469 52...."
Blankenfelde,110000030308,139.0,31894.980083,3.594962e+07,"MULTIPOLYGON (((13.39291 52.64565, 13.39279 52..."

Select year

In [67]:
mapyear = 1984

Create empty column in district database which will count the occurrences of stops connected to Wilmersdorf for each district, and add to dataframe

In [68]:
num_kreuzberg = [0]*len(berlin_gdf["schlüssel"])

In [69]:
berlin_gdf.insert(5,"num_kreuzberg",num_kreuzberg)

Filter by year

In [70]:
Kreuzberg_connected_stations_df_mapping = Kreuzberg_connected_stations_df[Kreuzberg_connected_stations_df["year"]==str(mapyear)]
Kreuzberg_connected_stations_df_mapping

,stop_id,year,stop_name,typ,standort,in_linien,Point,wikidata_id,Kreuzberg_connected
15178,19841,1984,Adalbertstr.,autobus,"52.50548699996121, 13.42221404498021","['75', '78', '78E']",POINT (13.42221 52.50549),NaN,True
15182,19845,1984,Adenauerplatz,u-bahn,"52.499722, 13.307222",['7'],POINT (13.30722 52.49972),Q570939,True
15185,19848,1984,Adolf-Scheidt-Platz/Krankenhaus,autobus,"52.47818518185836, 13.37828632745728",['96'],POINT (13.37829 52.47819),NaN,True
15186,19849,1984,Adolf-Schiedt-Platz,autobus,"52.47820407312392, 13.378388543559256",['96E'],POINT (13.37839 52.4782),NaN,True
15188,198411,1984,Afrikanischestr.,u-bahn,"52.560027777778,13.334633333333",['6'],POINT (13.33463 52.56003),Q559239,True
...,...,...,...,...,...,...,...,...,...
17054,19841877,1984,Yorckstr.,s-bahn,"52.491777777778,13.372141666667",['2'],POINT (13.37214 52.49178),Q21776729,True
17055,19841878,1984,Yorckstr.,u-bahn,"52.493056,13.370833",['7'],POINT (13.37083 52.49306),Q12011022,True
17056,19841879,1984,Yorckstr./Rathaus Kreuzberg,autobus,"52.49337476342669, 13.385163988079599",['28'],POINT (13.38516 52.49337),NaN,True
17079,19841902,1984,Zoologischer Garten,u-bahn,"52.5058669,13.3330236","['1', '9']",POINT (13.33302 52.50587),Q4024764,True
17086,19841909,1984,Zwickauerdamm,u-bahn,"52.423333333333,13.483888888889",['7'],POINT (13.48389 52.42333),Q572096,True

For each station check if it is in each district, increase num_Kreuzberg value by 1 for the district each stop is in

In [71]:
for i,point in enumerate(Kreuzberg_connected_stations_df_mapping["Point"]): # iterates over all stations connected to Kreuzberg
    for j,district in enumerate(berlin_gdf["schlüssel"]): # iterates over all possible districts in Berlin
        if point.within(berlin_gdf["geometry"][j]): # checks whether the station is in each of the districts
            berlin_gdf["num_kreuzberg"][j] += 1 # adds the station to the district it is within (numerically)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/geopandas/geoseries.py:772: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  val = getattr(super(), mtd)(*args, **kwargs)
/var/folders/l_/x12p1dds19n9lv81bj_mbs0m0000gn/T/ipykernel_15700/1649983148.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  berlin_gdf["num_kreuzberg"][j] += 1 # adds the station to the district it is within (numerically)
/var/folders/l_/x12p1dds19n9lv81bj_mbs0m0000gn/T/ipykernel_15700/1649983148.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  berlin_gdf["num_kreuzberg"][j] += 1 # adds the station to the district it is within (numerically)
/var/folders/l_/x12p1dds19n9lv81bj_mbs0m0000gn/T/ipykernel_15700/1649983148.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  berlin_gdf["num_kreuzberg"][j] += 1 # adds the station to the district it is within (numerically)

Export to json for mapping

In [72]:
berlin_gdf.to_file(f"/Users/katharinajennrich/Documents/Ancient Studies Sem. 5/Intro to DH/AnalysisDataset/stations_bydistrict_Kreuzberg_{mapyear}.json",driver="GeoJSON")

Export to csv for human review

In [73]:
berlin_gdf.to_csv(f"/Users/katharinajennrich/Documents/Ancient Studies Sem. 5/Intro to DH/AnalysisDataset/stations_bydistrict_Kreuzberg_{mapyear}.csv")